### ISSUE TITLE
gaussNorm fails on subset of a larger flowset

### ISSUE THREAD

**Issue by AndyinMission** [RGLab/flowStats#20]
I'm able to run gaussNorm on a flowset of 54 files specifying only the flowset and channel.names args, but if I run it on elements 1:5 of the same set to test conditions, it fails with this error, even with using the minimal set of args:

`Error in extract.base.landmarks(lms$filter, channel.names, max.lms) : `

Not sure whether this is a bug or not, but it's difficult to troubleshoot and hard to imagine how it will fail on a subset of files where it runs successfully on the full set.  All files have 10,000 cell events.

I can provide additional details or test files if needed, these files are from an image cytometer (Imagestream), but they seem to follow fcs file format specifications and I've typically not had trouble in other packages, for example using flowCore or flowClust to operate on them.

**Comment by mikejiang** [comment]
Could  you provide the link to the data and reproducible code?

**Comment by AndyinMission** [comment]
FCS files and code to reproduce error can be found here:

https://drive.google.com/open?id=0B1ppj6LgpY6sUTNvSDlHTXdZQTQ

Thanks!

**Comment by mikejiang** [comment]
Here I reproduced your error
```r
> fs_scaled1 <- gaussNorm(smallset, channel.names=mycolnames) 
No curve with  2  landmarks was found for channel  Intensity_AdaptiveErode.M01..BF..80._DHR . Decrease max.lms[ Intensity_AdaptiveErode.M01..BF..80._DHR ] and try again.
Error in extract.base.landmarks(lms$filter, channel.names, max.lms) : 
```
As it signals, something is wrong with the channel `Intensity_AdaptiveErode.M01..BF..80._DHR .`
And it is usually helpful to plot that channel with the stacked density plot (using latest ggcyto feature mentioned [here](https://github.com/RGLab/ggcyto/issues/21#issuecomment-315430674))
```r
test.chnl <- "Intensity_AdaptiveErode.M01..BF..80._DHR"
ggcyto(smallset, aes_string(x = test.chnl)) + geom_joy(aes(y = name)) + facet_null()
```
![image](https://user-images.githubusercontent.com/1385649/28849493-13850dec-76cc-11e7-9211-b92cd31f30cc.png)
This shows me that your data has not been transformed and I think normalization provided by flowStats typically does not work with raw scaled signal (@gfinak will correct me if I am wrong on this).
So I would transform the data first, here I only test on one channel, and apparently you can transform multiple channels all at once
```r
trans <- estimateLogicle(smallset[[1]], channels = test.chnl) 
smallset.trans <- transform(smallset, trans)
ggcyto(smallset.trans, aes_string(x = test.chnl)) + geom_joy(aes(y = name)) + facet_null()
```
![image](https://user-images.githubusercontent.com/1385649/28849677-04fc3466-76cd-11e7-8f3b-3c67da7eb8b3.png)
now you can see the transformed data looks easier for `gaussNorm` to work with, and it did succeed this time (again I am only demonstrate it on one channel)
```r
> fs_scaled1 <- gaussNorm(smallset.trans, channel.names=test.chnl)
Adjusting the distance between landmarks
....
```
Now the data is normalized (it doesn't change too much but you can still see the difference after the 
 peak alignment especially the second sample from the top)
```r
ggcyto(fs_scaled1[["flowset"]], aes_string(x = test.chnl)) + geom_joy(aes(y = name)) + facet_null()
```
![image](https://user-images.githubusercontent.com/1385649/28849835-dc25b688-76cd-11e7-9d2a-6a83a21997d8.png)

**Comment by AndyinMission** [comment]
Thanks Mike.  You're correct, I've not been using a transformation with these files but it seems that's the problem.  Thanks again for having a look at this.
