### ISSUE TITLE
workflow class deprecated

### ISSUE THREAD

**Issue by abbatidanilo** [RGLab/flowStats#26]
To start the analysis for flowStats from a flowSet, you need to start from a workflow, but the workflow class has been deprecated since a while. See the warning message from the flowCore package:
_wf <- flowCore::workFlow(fS)
'flowCore::workFlow' is deprecated.
Use 'flowWorkspace::GatingSet' instead._
Which is the updated pipeline to be used instead of the one depicted in your vignette?

**Comment by jacobpwagner** [comment]
I recently updated the vignette to reflect the deprecation of the `workFlow` class:
381d7a29978a73e4cf4a12d67ff28bdc70e3c049

That change isn't in the Bioconductor 3.9 release, however, so you will need to either install the 3.10 development version or install from this repo. I also have not completely finished changing the plotting code over from `flowViz` to the more actively supported `ggcyto`, but I will finish that up soon.

The quick answer is that the updated pipeline uses `GatingSet` instead of `workFlow`, but the general flow of the analysis remains the same.

**Comment by abbatidanilo** [comment]
Thanks a lot Jack...
I am always  scared when I meet such a "deprected" messages... It means "_soon or later your code is not going to work anymore_"...
In this case I think you are not going to change this soon. I'll wait for the next official release.
Cheers

**Comment by jacobpwagner** [comment]
No problem. Just keep in mind that the `workFlow` class will actually be defunct and unavailable in the Bioconductor 3.10 release, so it may be a good idea to get more familiar with the `GatingSet` class for this purpose. The `flowWorkspace` and `openCyto` vignettes cover how to add compensation, transformation, and gating for `GatingSet`'s in more detail. Feel free to reach out here with issues if any questions arise.

**Comment by abbatidanilo** [comment]
Hello Jacob,
I just updated to bioconductor 3.9 and I tried to install the development version with
```r
 devtools::install_github("RGLab/flowStats")
```
And I got:

*Downloading GitHub repo RGLab/flowStats@master
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/RGLab/flowStats/tarball/master'*

could you please tell which is the right command to install the development version?
Otherwise we have a hole between the 3.8 version to the 3.9 in which the workFlow function is deprecated with no way to test your new implementation...
thanks!

**Comment by jacobpwagner** [comment]
@abbatidanilo, our repos follow the convention of calling the main branch "trunk" (typical in svn) rather than "master". `devtools::install_github` defaults to `ref = "master"`. That explains the error you're getting. Try this and let me know if you run in to any more issues:

```
devtools::install_github("RGLab/flowStats", ref = "trunk")
```

**Comment by abbatidanilo** [comment]
Hello Jacob
It didn't work properly
this is what I got:
The downloaded source packages are in
	‘C:\Users\abbat\AppData\Local\Temp\RtmpK4nsUu\downloaded_packages’
> devtools::install_github("RGLab/flowCore", ref = "trunk")
Downloading GitHub repo RGLab/flowCore@trunk
√  checking for file 'C:\Users\abbat\AppData\Local\Temp\RtmpK4nsUu\remotes30f839115dbb\RGLab-flowCore-caf6ee4/DESCRIPTION' ...
-  preparing 'flowCore': (757ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (952ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects:  'flowCore/tests/testthat/expectResults.rds'
-  building 'flowCore_1.51.7.tar.gz'
   
* installing *source* package 'flowCore' ...
** using staged installation
** libs
Error: package 'cytolib' 1.6.0 was found, but >= 1.7.2 is required by 'flowCore'
* removing 'C:/R/R-3.6.0/library/flowCore'
* restoring previous 'C:/R/R-3.6.0/library/flowCore'
Error: Failed to install 'flowCore' from GitHub:
  (converted from warning) installation of package ‘C:/Users/abbat/AppData/Local/Temp/RtmpK4nsUu/file30f8add73/flowCore_1.51.7.tar.gz’ had non-zero exit status


> devtools::install_github("RGLab/flowStats", ref = "trunk")
Downloading GitHub repo RGLab/flowStats@trunk
√  checking for file 'C:\Users\abbat\AppData\Local\Temp\RtmpK4nsUu\remotes30f83c1440b4\RGLab-flowStats-14957aa/DESCRIPTION' ... 
-  preparing 'flowStats':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'flowStats_3.43.8.tar.gz'
   
* installing *source* package 'flowStats' ...
** using staged installation
** R
** data
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'flowCore' 1.50.0 is being loaded, but >= 1.51.6 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'flowStats'
* removing 'C:/R/R-3.6.0/library/flowStats'
* restoring previous 'C:/R/R-3.6.0/library/flowStats'
Error: Failed to install 'flowStats' from GitHub:
  (converted from warning) installation of package ‘C:/Users/abbat/AppData/Local/Temp/RtmpK4nsUu/file30f85d67387/flowStats_3.43.8.tar.gz’ had non-zero exit status

besides I fear I also have to update the openCyto package to the devel version 
which is also a pain...

**Comment by gfinak** [comment]
@abbatidanilo,  you need to upgrade (in this order):
```
cytolib
flowCore
ncdfFlow
flowWorkspace
flowStats
CytoML
openCyto
```
all from `ref="trunk"`

This "bug" is fixed in the current version, as far as we can tell. Even if it wasn't and were to provide fix for you, it would appear in the development versions and you would still have to update all these packages.
