### ISSUE TITLE
gs_pop_add() function referenced in vignette

### ISSUE THREAD

**Issue by jeremycfd** [RGLab/flowStats#27]
Hello,

You utilize a function called gs_pop_add() in your vignette, but I've been unable to locate this function in any current R package. I got the sense that this may have been replaced by the add() function in the flowWorkspace package, but replacing gs_pop_add(gs, lg) with add(gs, lg) in your vignette doesn't work.

Thanks!

**Comment by mikejiang** [comment]
`add` is deprecated by `gs_pop_add` in the latest bioc development or github trunk branch. Both are defined in `flowWorkspace` so check your package version of `flowWorkspace`

**Comment by jeremycfd** [comment]
Ah, thanks. Turns out the github installation of most recent version of flowWorkspace was failing because I also needed to install RProtoBufLib, cytolib, flowCore, ncdfFlow, and flowStats from github repo as well (versions from Bioc were causing problems). 

Thanks!
