### ISSUE TITLE
normQA error

### ISSUE THREAD

**Issue by danxfreeman** [RGLab/flowStats#30]
I get the following error message when I run normQA on my dataset:

`Error in range(data[[1]])[, p][1, ] : incorrect number of dimensions`

I can fix it by copying the function from GitHub and removing the commas from this line:

`xvals <- seq(range(data[[1]])[, p][1], range(data[[1]])[, p][2], len=np)`

**Comment by jacobpwagner** [comment]
Yeah, it looks like it might have not been factoring in the default `drop=TRUE` so it was indexing in to a one-column dataframe instead of the simplified vector. That should be fixed now.

**Comment by danxfreeman** [comment]
It works great now, thanks Jacob!
