### ISSUE TITLE
Incorrect maintainer

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowStats#31]
Hi,

This Rd document wrongly states the maintainer.

https://github.com/RGLab/flowStats/blob/f4e2acdd8a6bfab06d372529a6f79fd8ec6b3085/man/flowStats-package.Rd#L39

**Comment by jacobpwagner** [comment]
Thanks @SamGG . Fixed it. The docs for this package are still mostly manually maintained (not roxygen) so the maintainer just never got updated.
