### ISSUE TITLE
data description of ITN dataset

### ISSUE THREAD

**Issue by DaigoOkada** [RGLab/flowStats#36]
The built-in dataset ITN contains  3 patient groups with 5 samples each (group 1, 5 and 6). What is the difference among the patient groups? I couldn't find in the reference manual or other Web source. The reference manual of the package says the source of data is Immune Tolerance Network. Is there any paper or document which provided the detail description of this dataset?

**Comment by mikejiang** [comment]
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3648208/

**Comment by DaigoOkada** [comment]
Thank you very much for the information.
